---
driver:
  name: docker
  use_sudo: false
  privileged: true
  #socket: npipe:////./pipe/docker_engine # If you are using Docker for Windows, make sure this setting is enabled.

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  playbook: default.yml
  roles_path: ../ansible-test-framework/ # replace with the name of your role
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
- name: centos6-ansible-latest
  driver:
    image: rndmh3ro/docker-centos6-ansible:latest
    platform: centos
- name: centos7-ansible-latest
  driver:
    image: rndmh3ro/docker-centos7-ansible:latest
    platform: centos
- name: oracle6-ansible-latest
  driver:
    image: rndmh3ro/docker-oracle6-ansible:latest
    platform: centos
- name: oracle7-ansible-latest
  driver:
    image: rndmh3ro/docker-oracle7-ansible:latest
    platform: centos
- name: ubuntu1204-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1204-ansible:latest
    platform: ubuntu
- name: ubuntu1404-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1404-ansible:latest
    platform: ubuntu
- name: ubuntu1604-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1604-ansible:latest
    platform: ubuntu
- name: debian7-ansible-latest
  driver:
    image: rndmh3ro/docker-debian7-ansible:latest
    platform: debian
- name: debian8-ansible-latest
  driver:
    image: rndmh3ro/docker-debian8-ansible:latest
    platform: debian
- name: debian9-ansible-latest
  driver:
    image: rndmh3ro/docker-debian9-ansible:latest
    platform: debian

suites:
- name: ansible
